src/main/resources/static/css/member.css
src/main/resources/static/css/sangbum.css
src/main/resources/templates/common/userheader.html
src/main/resources/templates/member/regist.html

회원가입을 위한 regist.html을 디자인했습니다.

[DESIGN] 회원관리 회원가입 디자인

---

src/main/resources/static/css/notice.css
src/main/resources/templates/notice/list.html

[TEMPSAVE] 임시저장

---

.idea/dataSources.xml
src/main/java/com/greedy/dduckleaf/authentication/model/dto/CustomUser.java
src/main/java/com/greedy/dduckleaf/member/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/member/entity/Member.java
src/main/resources/application.yml
src/main/resources/templates/member/login.html

DB컬럼와 컬럼이 일치하지않아  MemberDTO, Member, CustomUser를 변경했습니다.

[FIX] 회원관리 로그인 오류수정

---

src/main/resources/templates/common/adminheader.html
src/main/resources/templates/common/userheader.html

헤더 이미지,CSS,JS 경로 수정을 위해 adminheader.html, userheader.html을 변경했습니다.

[STYLE]  헤더 이미지,CSS,JS 경로 수정

---

src/main/resources/templates/common/paging.html

타임리프 문법적용하여 페이징 파일 만들었습니다.
각자 테이블 하단에 include 하여 사용하시면 되고,
js 코드는 각자 html 파일에 각자 작성해야할거예요!
js코드 완성되는대로 공유하도록 하겠습니다.

[DESIGN] 공통 사용 페이징 HTML 파일 추가

---

src/main/resources/templates/common/paging.html

기존에 작성한 것이 springadata 용 페이징코드가 아니어서 수정해서 다시 올립니다!!!

[DESIGN] 공통사용 페이징 HTML 전면수정

---

src/main/resources/static/css/projectqa.css
src/main/resources/templates/projectqa/list.html

projectqa  list.html디자인 완료했습니다.

[DESIGN] 프로젝트 문의 서포터 조회 디자인

---

src/main/resources/templates/fee/regist.html

[DESIGN] 수수료율 등록 디자인

---

src/main/resources/templates/fee/modify.html

[DESIGN] 수수료율 수정 디자인

---

src/main/resources/templates/faq/detail.html

[DESIGN] Faq detail 화면 디자인

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/resources/templates/project/end/detail.html
src/main/resources/templates/project/notice/detail.html
src/main/resources/templates/project/notice/list.html

Controller부터 html 연동되게 작업했습니다.

[FIX] 프로젝트 공지사항 조회 뷰 페이지와 연동 작업

---

src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/repository/MemberRepository.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java
src/test/java/com/greedy/dduckleaf/member/repository/MemberRepositoryTest.java
src/test/java/com/greedy/dduckleaf/member/service/MemberServiceTest.java

회원가입을 위한 휴대폰 인증번호 전송 기능을 구현했습니다.

[FEAT] 회원관리 휴대폰 인증번호 전송

---

src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java
src/test/java/com/greedy/dduckleaf/member/repository/MemberRepositoryTest.java
src/test/java/com/greedy/dduckleaf/member/service/MemberServiceTest.java

회원가입을 위한 아이디 중복 확인 기능을 구현했습니다.

[FEAT] 회원관리 아이디 중복 확인

---

src/main/java/com/greedy/dduckleaf/authentication/model/dto/CustomUser.java
src/main/java/com/greedy/dduckleaf/authentication/model/service/AuthenticationServiceImpl.java
src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/member/entity/Member.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java

떡잎펀드 서비스 이용을 위한 회원가입 기능을 구현했습니다.

[FEAT] 회원관리 회원가입

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/java/com/greedy/dduckleaf/projectnotice/service/ProjectNoticeService.java

[FEAT] 프로젝트 공지사항 작성하기

---

src/main/resources/static/css/projectNotice.css
src/main/resources/templates/project/notice/regist.html

마이페이지 파머탭에서 프로젝트 공지사항 작성하기 위한 페이지인 regist.html을 디자인했습니다.

[DESIGN] 프로젝트 공지사항 작성 폼 디자인

---

src/main/resources/templates/report/list.html

타임리프 문법 수정하여 표 안에 데이터가 출력될 수 있도록 했습니다.

[FIX] 회원번호로 프로젝트신고내역 목록조회 데이터 연동

---

src/main/resources/static/css/project.css
src/main/resources/static/css/projectNotice.css
src/main/resources/templates/project/end/noticedetail.html
src/main/resources/templates/project/notice/detail.html

마이페이지 파머탭에서 프로젝트 상세조회를 위한 페이지인 detail.html을 디자인했습니다.

[DESIGN] 프로젝트 공지사항 상세조회 디자인

---

src/main/resources/templates/common/project.html

마이페이지 파머탭에서 진행예정프로젝트, 진행 중 프로젝트용 메뉴바를 디자인했습니다.

[DESIGN] 파머탭 진행예정프로젝트, 진행 중 프로젝트 메뉴바 디자인

---

src/main/resources/templates/common/endproject.html

마이페이지 파머탭에서 진행완료 프로젝트용 메뉴바를 디자인했습니다.

[DESIGN] 파머탭 진행완료 프로젝트 메뉴바 디자인

---

src/main/resources/static/css/projectNotice.css
src/main/resources/templates/project/notice/list.html

마이페이지 파머탭에서 프로젝트 공지사항 목록조회를 위한 페이지인 list.html을 디자인했습니다.

[DESIGN] 프로젝트 공지사항 목록조회 디자인

---

src/test/java/com/greedy/dduckleaf/mockfund/controller/MockFundControllerTest.java
src/test/java/com/greedy/dduckleaf/mockfund/repository/MockFundInfoRepositoryTest.java
src/test/java/com/greedy/dduckleaf/mockfund/repository/MockFundRepositoryTest.java
src/test/java/com/greedy/dduckleaf/mockfund/repository/MockFundRewardRepositoryTest.java
src/test/java/com/greedy/dduckleaf/mockfund/repository/RewardCategoryRepositoryTest.java
src/test/java/com/greedy/dduckleaf/mockfund/service/MockFundServiceTest.java

모의펀딩 신청 관련 Controller, Service, Repository에 대한 테스트 코드를 추가했습니다.

[TEST] 모의펀딩 신청 페이지 테스트 코드 추가

---

src/main/java/com/greedy/dduckleaf/mockfund/controller/MockFundController.java
src/main/java/com/greedy/dduckleaf/mockfund/dto/MockFundInfoDTO.java
src/main/java/com/greedy/dduckleaf/mockfund/repository/FarmerRepository.java
src/main/java/com/greedy/dduckleaf/mockfund/repository/MockFundInfoRepository.java
src/main/java/com/greedy/dduckleaf/mockfund/repository/MockFundRewardRepository.java
src/main/java/com/greedy/dduckleaf/mockfund/repository/RewardCategoryRepository.java

[FIX] 모의펀딩 Repository 어노테이션 추가, Controller 매핑 경로 및 DTO 자료형 변경

---

src/main/resources/static/css/projectNotice.css
src/main/resources/templates/common/project.html
src/main/resources/templates/projectnotice/detail.html
src/main/resources/templates/projectnotice/list.html
src/main/resources/templates/projectnotice/modify.html
src/main/resources/templates/projectnotice/regist.html

마이페이지 파머탭에서 프로젝트 공지사항 수정하기 위한 페이지인 modify.html을 디자인했습니다.

[DESIGN] 프로젝트 공지사항 수정 페이지 디자인 완료

---

src/main/java/com/greedy/dduckleaf/email/EmailSender.java
src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/repository/MemberRepository.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java
src/test/java/com/greedy/dduckleaf/member/repository/MemberRepositoryTest.java
src/test/java/com/greedy/dduckleaf/member/service/MemberServiceTest.java

[FEAT] 회원관리 아이디 찾기 구현

---

src/main/java/com/greedy/dduckleaf/projectreport/controller/ProjectReportController.java
src/main/resources/templates/report/platformmanager/default.html
src/main/resources/templates/report/platformmanager/list.html

[FEAT] 프로젝트 목록 전체조회(관리자) 데이터 연동 완성

---

src/main/java/com/greedy/dduckleaf/projectreport/find/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/projectreport/find/dto/ProjectReportDTO.java
src/main/java/com/greedy/dduckleaf/projectreport/find/entity/ProjectReport.java

번거롭게 해드려 죄송합니다!! 
데이터 연동 중 누락된 DTO클래스로 인한 오류를 발견하여 엔티티와 DTO 관련 커밋사항 분류해 올립니다.

[FEAT] 프로젝트 신고내역 목록조회 시 필요한 DTO클래스 추가 및 기존 엔티티 수정

---

src/main/resources/static/css/member.css
src/main/resources/templates/member/login.html

[DESIGN] 회원관리 로그인 화면 수정

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/java/com/greedy/dduckleaf/projectnotice/repository/ProjectNoticeRepository.java
src/main/java/com/greedy/dduckleaf/projectnotice/service/ProjectNoticeService.java

[FEAT] 프로젝트 공지사항 수정 기능 구현

---

src/main/resources/templates/report/platformmanager/detail.html

타임리프 코드와 약간의 자바스크립트 코드 수정을 남겨두고 HTML틀은 완성헀습니다.

[DESIGN] 프로젝트신고내역 상세조회(관리자) HTML파일 추가

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/resources/templates/projectnotice/detail.html
src/main/resources/templates/projectnotice/list.html
src/main/resources/templates/projectnotice/modify.html
src/main/resources/templates/projectnotice/regist.html

프로젝트 공지사항 수정기능과 삭제 기능 뷰페이지와 연동하였습니다.

[FEAT] 프로젝트 공지사항 수정 삭제 기능 연동

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/java/com/greedy/dduckleaf/projectnotice/service/ProjectNoticeService.java

[FIX] 프로젝트 공지사항 삭제기능 수정

---

src/main/resources/static/css/member.css
src/main/resources/templates/member/regist.html

regist.html에 css가 적용되지않아 수정했습니다.

[DESIGN] 회원관리 회원가입 수정

---

src/main/java/com/greedy/dduckleaf/funding/regist/controller/FundingRegistController.java
src/main/java/com/greedy/dduckleaf/funding/regist/entity/Funding.java
src/main/java/com/greedy/dduckleaf/funding/regist/repository/PaymentHistoryForFundingRepository.java
src/main/java/com/greedy/dduckleaf/funding/regist/repository/ShippingAddressForFundingRepository.java
src/main/java/com/greedy/dduckleaf/funding/regist/service/FundingRegistService.java
src/main/resources/templates/funding/regist/fundingamount.html
src/main/resources/templates/funding/regist/shippinginfo.html

[FEAT] 펀딩신청시 동시 삽입되는 데이터 삽입 구현

---

src/main/resources/templates/report/platformmanager/detail.html
src/main/resources/templates/report/platformmanager/list.html
src/main/resources/templates/report/platformmanager/regist.html

타임리프 적용과 약간의 JS코드 수정은 추후 데이터연동 작업 시 마무리하겠습니다.
생각을 잘못해서 모달창을 만들어버려가지고 수정하는데 한참걸렸네요 ㅠ~~ 머지하고 바로 다음 작업 하겠습니다.

[DESIGN] 프로젝트신고답변 등록용 화면구현 HTML 파일 완성

---

src/main/resources/static/css/notice.css
src/main/resources/templates/notice/regist.html

[DESIGN] 공지사항 작성 화면 수정

---

src/main/resources/templates/mockfund/regist/basicinfo.html

모의펀딩 기본정보 업데이트 기능을 뷰 페이지와 연동했습니다.

[FEAT] 모의펀딩 기본정보 업데이트 기능 연동

---

src/main/java/com/greedy/dduckleaf/mockfund/controller/MockFundController.java
src/main/java/com/greedy/dduckleaf/mockfund/dto/MockFundDTO.java
src/main/java/com/greedy/dduckleaf/mockfund/dto/MockFundInfoDTO.java
src/main/java/com/greedy/dduckleaf/mockfund/entity/MockFundInfo.java
src/main/java/com/greedy/dduckleaf/mockfund/repository/MockFundInfoRepository.java
src/main/java/com/greedy/dduckleaf/mockfund/service/MockFundService.java

[FEAT] 모의펀딩 기본정보 업데이트 기능 추가

---

src/main/resources/templates/notice/list.html

[DESIGN] 공지사항 목록조회 디자인 수정

---

src/main/resources/templates/notice/detail.html

[DESIGN] 공지사항 상세조회 디자인 수정

---

src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/java/com/greedy/dduckleaf/projectnotice/dto/ProjectProgressStatusDTO.java
src/main/java/com/greedy/dduckleaf/projectnotice/entity/Project.java
src/main/java/com/greedy/dduckleaf/projectnotice/entity/ProjectProgressStatus.java
src/main/java/com/greedy/dduckleaf/projectnotice/repository/ProjectNoticeRepository.java
src/main/java/com/greedy/dduckleaf/projectnotice/repository/ProjectRepository.java
src/main/java/com/greedy/dduckleaf/projectnotice/service/ProjectNoticeService.java
src/test/java/com/greedy/dduckleaf/projectnotice/repository/ProjectNoticeRepositoryTest.java

회원 번호로 진행중인 프로젝트 번호를 조회할 수 있는 메소드 추가했습니다.
프로젝트 공지사항 목록 조회 메소드 수정, 주석 작성하였습니다.

[FEAT] 회원 정보로 프로젝트 번호 조회 메소드 추가 작성

---

src/main/resources/static/css/projectnotice.css
src/main/resources/templates/projectnotice/detail.html
src/main/resources/templates/projectnotice/list.html
src/main/resources/templates/projectnotice/modify.html
src/main/resources/templates/projectnotice/regist.html

[DESIGN] 파머탭 프로젝트 공지사항 뷰 수정

---

src/main/java/com/greedy/dduckleaf/funding/regist/controller/FundingRegistController.java
src/main/resources/templates/common/supporterpage.html
src/main/resources/templates/funding/find/supporter/fundinglist.html
src/main/resources/templates/funding/regist/fundingresult.html

[FEAT] 펀딩내역 조회 페이지와 핸들러메소드 연동

---

src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/resources/templates/member/find/id.html
src/main/resources/templates/member/find/success.html
src/main/resources/templates/member/login.html

[FEAT] 회원관리 아이디 찾기 페이지와 핸들러메소드 연동

---

src/main/resources/static/css/member.css

[DESIGN] 회원관리 아이디 찾기 페이지 수정

---

src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java

[HOTFIX] 회원관리 아이디 찾기 경로 수정

---

src/main/resources/templates/report/platformmanager/detail.html

타임리프 문법 적용하여 조회한 데이터를 브라우저에 출력하였습니다.

[FEAT] 프로젝트 신고내역 상세조회 데이터연동

---

src/main/resources/templates/report/platformmanager/detail.html

답변내용이 없는 경우, '답변이 존재하지 않습니다.' 라는 대체문구가 출력되도록 타임리프문법 수정해주었습니다.

[FEAT] 프로젝트 신고내역 상세조회(플랫폼) 데이터 연동 수정

---

src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/repository/MemberRepository.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java
src/test/java/com/greedy/dduckleaf/member/repository/MemberRepositoryTest.java
src/test/java/com/greedy/dduckleaf/member/service/MemberServiceTest.java

[FEAT] 회원관리 비밀번호 찾기 기능 구현

---

src/main/resources/templates/report/detail.html
src/main/resources/templates/report/platformmanager/detail.html

신고 상세조회 타임리프 문법수정하며, 유사한 기능에서 누락된 코드가 있어 추가로 작업해주었습니다.

[DESIGN] 프로젝트 신고내용 상세조회 화면 수정

---

src/main/java/com/greedy/dduckleaf/member/repository/MemberRepository.java

MemberService에 메소드가 누락되어있어 수정했습니다.

[HOTFIX] 회원관리 비밀번호 찾기 메소드 누락

---

src/main/resources/templates/project/regist/basicreq.html

프로젝트 신청 시 기본요건을 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 기본요건 작성 페이지 디자인

---

src/main/resources/templates/project/regist/story.html

프로젝트 신청 시 스토리를 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 스토리 작성 페이지 디자인

---

src/main/resources/templates/project/regist/basicinfo.html

프로젝트 신청 시 기본정보를 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 기본정보 작성 페이지 디자인

---

src/main/resources/templates/project/regist/reward.html

프로젝트 신청 시 리워드설계를 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 리워드설계 작성 페이지 디자인

---

src/main/resources/templates/project/regist/policy.html

프로젝트 신청 시 위험요인 및 정책을 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 위험요인 및 정책 작성 페이지 디자인

---

src/main/resources/templates/project/regist/farmerinfo.html

프로젝트 신청 시 파머정보를 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 파머정보 작성 페이지 디자인

---

src/main/resources/templates/project/regist/representative.html

프로젝트 신청 시 대표자 및 정산정보를 작성하는 페이지를 디자인했습니다.

[DESIGN] 프로젝트 신청 대표자 및 정산정보 작성 페이지 디자인

---

.idea/inspectionProfiles/Project_Default.xml
src/main/resources/static/css/member.css
src/main/resources/templates/member/find/modify.html
src/main/resources/templates/member/find/pwd.html

비밀번호를 찾는 pwd.html과 비밀번호를 변경하는 modify.html을 디자인했습니다.

[DESIGN] 회원관리 비밀번호 찾기 화면 작성

---

src/main/java/com/greedy/dduckleaf/common/paging/PagingForm.java
src/main/java/com/greedy/dduckleaf/funding/dto/FundingDTO.java
src/main/java/com/greedy/dduckleaf/funding/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/funding/dto/ProjectRegistInfoDTO.java
src/main/java/com/greedy/dduckleaf/funding/dto/ProjectRewardCategoryDTO.java
src/main/java/com/greedy/dduckleaf/funding/entity/Funding.java
src/main/java/com/greedy/dduckleaf/funding/entity/Project.java
src/main/java/com/greedy/dduckleaf/funding/entity/ProjectRegistInfo.java
src/main/java/com/greedy/dduckleaf/funding/entity/ProjectRewardCategory.java
src/main/java/com/greedy/dduckleaf/funding/find/member/service/FundingServiceForFind.java
src/test/java/com/greedy/dduckleaf/funding/find/member/repository/FundingForMemberFindRepositoryTest.java

[FEAT] 펀딩 목록 조회기능 작성

---

src/main/java/com/greedy/dduckleaf/notice/controller/NoticeController.java
src/main/java/com/greedy/dduckleaf/notice/repository/NoticeRepository.java
src/main/java/com/greedy/dduckleaf/notice/service/NoticeService.java
src/test/java/com/greedy/dduckleaf/notice/controller/NoticeControllerTest.java
src/test/java/com/greedy/dduckleaf/notice/repository/NoticeRepositoryTest.java
src/test/java/com/greedy/dduckleaf/notice/service/NoticeServiceTest.java

[FEAT] 공지사항 수정하기 기능 추가

---

src/main/java/com/greedy/dduckleaf/mockfund/controller/MockFundController.java
src/main/java/com/greedy/dduckleaf/mockfund/dto/MockFundInfoDTO.java
src/main/java/com/greedy/dduckleaf/mockfund/entity/MockFundInfo.java
src/main/java/com/greedy/dduckleaf/mockfund/service/MockFundService.java

모의펀딩 스토리 프로젝트 요약 내용과 동의확인 여부 수정기능을 추가했습니다.

[FEAT] 모의펀딩 스토리 수정 기능 추가

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/Project.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectForApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/main/java/com/greedy/dduckleaf/projectnotice/controller/ProjectNoticeController.java
src/main/java/com/greedy/dduckleaf/projectnotice/repository/ProjectForProjectNoticeRepository.java
src/main/java/com/greedy/dduckleaf/projectnotice/service/ProjectNoticeService.java

repository 동일 이름 사용으로 인한 테스트 코드 에러 발생으로 repository 이름 수정했습니다.

[HOTFIX] 테스트 코드 에러 발생 수정

---

src/main/resources/templates/member/find/id.html
src/main/resources/templates/member/find/success.html

id.html과 success.html에서 요청 경로와 script부분을 수정하였습니다.

[FIX] 회원관리 아이디 찾기

---

dduckleaf.iml
pom.xml
src/main/java/com/greedy/dduckleaf/member/controller/MemberController.java
src/main/java/com/greedy/dduckleaf/member/service/MemberService.java
src/test/java/com/greedy/dduckleaf/member/service/MemberServiceTest.java

MemberController에서 필요한 메소드를 추가, 수정 하였습니다.

[FIX] 회원관리 비밀번호 찾기 메소드 추가

---

src/main/resources/templates/member/find/modify.html
src/main/resources/templates/member/find/pwd.html

비밀번호 찾기 페이지와 핸들러 메소드를 연결하였습니다.

[FEAT] 회원관리 비밀번호 찾기 연동작업

---

src/main/resources/templates/common/menubar.html

프로젝트 오픈 신청 페이지로 이어지는 링크 연결했습니다.

[DESIGN] 유저 메뉴바 링크 연결

---

src/main/resources/templates/report/projectmanager/list.html

[DESIGN] 프로젝트별 신고목록조회 VIEW 구현

---

src/main/resources/templates/mockfund/regist/reward.html

모의펀딩 리워드 정보 업데이트 기능을 뷰 페이지와 연동했습니다.

[FEAT] 모의펀딩 리워드 정보 업데이트 기능 연동

---

src/main/resources/templates/mockfund/regist/story.html

[STYLE] 스토리 view 페이지 쓰지 않는 주석 제거

---

src/main/resources/static/css/faq.css
src/main/resources/templates/faq/list.html

faq목록조회를 할수있는 list.html을 작성했습니다.

[DESIGN] faq 목록조회 페이지 작성

---

src/main/java/com/greedy/dduckleaf/faq/controller/FaqController.java
src/main/java/com/greedy/dduckleaf/faq/dto/FaqDTO.java
src/main/java/com/greedy/dduckleaf/faq/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/faq/entity/Faq.java
src/main/java/com/greedy/dduckleaf/faq/entity/Member.java
src/main/java/com/greedy/dduckleaf/faq/repository/FaqRepository.java
src/main/java/com/greedy/dduckleaf/faq/service/FaqService.java
src/test/java/com/greedy/dduckleaf/faq/controller/FaqControllerTest.java
src/test/java/com/greedy/dduckleaf/faq/repository/FaqRepositoryTest.java
src/test/java/com/greedy/dduckleaf/faq/service/FaqServiceTest.java

[FEAT] faq 목록조회 구현

---

src/main/resources/static/css/projectapplication.css

[DESIGN] CSS 수정

---

src/main/resources/templates/report/projectmanager/detail.html

[DESIGN] 프로젝트 신고 상세조회 (관리자 프로젝트관리 메뉴) 화면구현

---

src/main/java/com/greedy/dduckleaf/projectreport/controller/ProjectReportController.java

프로젝트관리 메뉴 하위에서 답변을 등록하는 백엔드로직을 구현했습니다.
서비스클래스, 레파지토리 클래스에서는 메소드를 재사용하였기 때문에 컨트롤러 클래스만 새롭게 작성해주었습니다.

[FEAT] 프로젝트 신고 답변 등록 기능 추가

---

src/main/resources/templates/report/platformmanager/detail.html
src/main/resources/templates/report/platformmanager/list.html
src/main/resources/templates/report/projectmanager/detail.html
src/main/resources/templates/report/projectmanager/list.html

게시글 등록 시 사용자의 실수로 등록이 되는 것을 방지하고자 유효성 검증을 추가해주었습니다. (onsubmit)
게시글이 등록되고 목록으로 redirect시 사용자가 게시물이 정상 등록되었는지 확인할 수 있도록 alert창을 띄워주었습니다.

[DESIGN] 프로젝트 신고 답변 등록 기능 수정

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/FarmerFinancialInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/FarmerInfoForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectApplicationInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectBasicInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectForApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectRewardCategoryForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectShippingInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/RefundPolicyForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/RewardRegistInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/repository/ProjectRepository.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

[FEAT] 프로젝트 기본 정보 수정 기능

---

src/test/java/com/greedy/dduckleaf/myfunding/repository/FundingInfoForMyFundingRepositoryTest.java

테스트 코드를 삭제하지 않아 에러가 발생하는 부분을 수정하였습니다.

[HOTFIX] 마이펀딩 테스트코드에서 에러 발생

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/resources/templates/project/regist/basicinfo.html
src/main/resources/templates/project/regist/basicreq.html
src/main/resources/templates/project/regist/main.html

프로젝트 기본 정보 업데이트 기능을 뷰 페이지와 연동했습니다.

[FEAT] 프로젝트 신청 기본정보 업데이트 기능 연동

---

src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectBasicInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectShippingInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/RewardRegistInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/Project.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectRewardCategory.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectShippingInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/RewardRegistInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

[FIX] ProjectBasicInfo DTO타입변경으로 인한 오류 수정

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectBasicInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

[FEAT] 프로젝트 신청 스토리 작성 기능

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/resources/templates/project/regist/story.html

[FEAT] 프로젝트 신청 스토리 작성 기능 뷰페이지와 연동

---

src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectRewardCategory.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java

[STYLE] @Transactional 추가

---

src/main/resources/templates/mockfunding/list.html

[DESIGN] 모의펀딩 목록 조회 기능 구현 페이지 추가

---

src/main/resources/static/css/myfunding.css
src/main/resources/static/css/mypage.css
src/main/resources/templates/common/supporterpage.html
src/main/resources/templates/myfunding/default.html

[DESIGN] 마이펀딩 마이펀딩 조회 디자인

---

src/main/java/com/greedy/dduckleaf/faq/controller/FaqController.java
src/main/java/com/greedy/dduckleaf/faq/dto/FaqDTO.java
src/main/java/com/greedy/dduckleaf/faq/service/FaqService.java

[FEAT] FAQ 상세 조회

---

src/main/resources/static/css/faq.css
src/main/resources/templates/faq/detail.html
src/main/resources/templates/faq/list.html

[DESIGN] FAQ 상세조회 디자인

---

src/main/java/com/greedy/dduckleaf/project/controller/ProjectController.java
src/main/resources/templates/project/end/detail.html
src/main/resources/templates/project/progressing/detail.html
src/main/resources/templates/project/scheduled/detail.html

개별 프로젝트 상세 조회 뷰 페이지와 컨트롤러를 연결하였습니다.

[FEAT] 개별 프로젝트 상세 조회

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectShippingInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

[FEAT] 프로젝트 신청 리워드 작성 기능 구현

---

src/main/java/com/greedy/dduckleaf/project/dto/FarmerDTO.java
src/main/java/com/greedy/dduckleaf/project/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/project/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/project/dto/ProjectProgressStatusDTO.java
src/main/java/com/greedy/dduckleaf/project/entity/Farmer.java
src/main/java/com/greedy/dduckleaf/project/entity/Member.java
src/main/java/com/greedy/dduckleaf/project/entity/Project.java
src/main/java/com/greedy/dduckleaf/project/entity/ProjectProgressStatus.java
src/main/java/com/greedy/dduckleaf/project/repository/ProjectRepository.java
src/main/java/com/greedy/dduckleaf/project/service/ProjectService.java

[FEAT] 개별 프로젝트 상세 조회 기능 추가

---

src/main/java/com/greedy/dduckleaf/project/controller/ProjectController.java
src/main/java/com/greedy/dduckleaf/project/dto/FundingInfoDTO.java
src/main/java/com/greedy/dduckleaf/project/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/project/entity/FundingInfo.java
src/main/java/com/greedy/dduckleaf/project/entity/Project.java
src/main/java/com/greedy/dduckleaf/project/repository/FundingInfoForProjectDetailRepository.java
src/main/java/com/greedy/dduckleaf/project/repository/ProjectRepository.java
src/main/java/com/greedy/dduckleaf/project/service/ProjectService.java

프로젝트 디테일 조회에서 서포터 수와 남은 일자 조회 기능 추가했습니다.

[FEAT] 프로젝트 디테일 조회 기능 추가

---

src/main/java/com/greedy/dduckleaf/projectapplication/entity/Project.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectShippingInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectRewardCategoryForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java

@Transactional 누락으로 인한 오류 수정 및 주석 제거

[FIX] @Transactional 누락으로 인한 오류 수정

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectBasicInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/RefundPolicyDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/RewardRegistInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/RefundPolicyForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

프로젝트 신청 시 반환 정책을 작성하는 기능을 구현했습니다.

[FEAT] 프로젝트 신청 반환 정책 작성 기능

---

src/main/java/com/greedy/dduckleaf/projectapplication/dto/FarmerFinancialInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/RefundPolicyDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/FarmerFinancialInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/RefundPolicy.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java

프로젝트 신청 페이지에서 동의 버튼을 눌렀을 때 NULL값 인서트로 인해 발생하는 오류 수정했습니다.

[FIX] 동의 날짜에 NULL값 삽인으로 인한 오류 수정

---

src/main/resources/templates/profile/modify/email.html

이메일을 변경할 수 있는 email.html을 디자인 하였습니다.

[DESIGN] 프로필 이메일 변경

---

src/main/resources/static/css/projectlist.css

[DESIGN] 프로젝트 목록 css 수정

---

src/main/resources/static/css/profile.css
src/main/resources/templates/profile/modify/pwd.html

비밀번호를 변경할 수 있는 pwd.html페이지를 작성하였습니다.

[DESIGN] 프로필 비밀번호 변경 페이지

---

dduckleaf.iml
pom.xml
src/main/java/com/greedy/dduckleaf/profile/controller/ProfileController.java
src/main/java/com/greedy/dduckleaf/profile/dto/MemberDTO.java
src/main/java/com/greedy/dduckleaf/profile/dto/ProfileAttachmentDTO.java
src/main/java/com/greedy/dduckleaf/profile/entity/Member.java
src/main/java/com/greedy/dduckleaf/profile/entity/ProfileAttachment.java
src/main/java/com/greedy/dduckleaf/profile/repository/MemberForProfileRepository.java
src/main/java/com/greedy/dduckleaf/profile/repository/ProfileAttachmentForProfileRepository.java
src/main/java/com/greedy/dduckleaf/profile/service/ProfileService.java
src/main/java/com/greedy/dduckleaf/projectnotice/dto/ProfileDTO.java
src/test/java/com/greedy/dduckleaf/profile/repository/MemberForProfileRepositoryTest.java
src/test/java/com/greedy/dduckleaf/profile/repository/ProfileAttachmentForProfileRepositoryTest.java
src/test/java/com/greedy/dduckleaf/profile/service/ProfileServiceTest.java

[FEAT] 프로필 프로필 사진 조회

---

src/main/java/com/greedy/dduckleaf/profile/controller/ProfileController.java
src/main/java/com/greedy/dduckleaf/profile/service/ProfileService.java

회원의 프로필 사진정보를 변경하는 기능을 구현하였습니다.

[FEAT] 프로필 프로필 사진 변경

---

src/main/resources/static/css/settlement.css
src/main/resources/templates/common/endproject.html
src/main/resources/templates/settlement/farmer/overview.html

[DESIGN] 파머탭 완료된 프로젝트 정산금 조회 화면 구현

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/FarmerFinancialInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/Bank.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/FarmerFinancialInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/BankForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/FarmerFinancialInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/MemberForApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

프로젝트 신청  대표자 및 정산 정보 작성 기능을 구현했습니다.

[FEAT] 프로젝트 신청 대표자 및 정산 정보 작성 기능 구현

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectAttachment.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectAttachmentForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java

프로젝트 신청 시 기본 정보 작성 페이지에서 대표이미지 업로드 기능 구현했습니다.

[FEAT] 프로젝트 신청 기본 정보 대표이미지 업로드 기능 구현

---

src/main/java/com/greedy/dduckleaf/project/controller/ProjectManagerController.java
src/main/resources/templates/project/manage/end/endlist.html
src/main/resources/templates/project/manage/end/projectlistpaging.html

수정사항
1. 페이징 영역을 replace로 외부 html로 import형식으로 수정
2. 재사용을 위해 intent변수로 요청url 유동적으로 작동되도록 수정

[FEAT] 프로젝트관리 완료 프로젝트 목록조회 페이징 수정

---

src/main/resources/static/css/admin.css
src/main/resources/templates/project/manage/end/detail.html
src/main/resources/templates/project/manage/end/submenu.html

[DESIGN] 프로젝트관리 > 개별프로젝트 상세조회 화면 구현

---

src/main/resources/static/css/funding.css
src/main/resources/templates/common/supporterpage.html
src/main/resources/templates/funding/find/supporter/fundinglist.html

[DESIGN] 서포터페이지 펀딩목록 페이지 작성

---

src/main/java/com/greedy/dduckleaf/funding/find/member/controller/FundingForMemberFindController.java
src/main/java/com/greedy/dduckleaf/funding/find/member/repository/FundingForMemberFindRepository.java
src/main/java/com/greedy/dduckleaf/funding/find/member/service/FundingServiceForFind.java

4/24일 시작했던 펀딩목록조회 8일 후 오늘 페이징처리까지 적용해서 드디어 끝냈습니다~
구현이 막막~~해도 즐기면서 해봅시다~~
밑에 링크는 선물입니다~
https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FdNoiDz%2FbtqxRuPsiEl%2FCGfDTFSpKlQlQQSWCYfBJ0%2Fimg.jpg

[FEAT] 서포터페이지 펀딩목록조회 작성

---

src/main/resources/static/css/admin.css
src/main/resources/templates/project/manage/end/detail.html
src/main/resources/templates/project/manage/end/submenu.html

관리자>프로젝트관리페이지>프로젝트 상세조회 화면에 필요한 프로젝트 정보 데이터를 연동하였습니다.
펀딩내역관리, 정산금관리, 발송관리, 환불관리 하시는 팀원들은
project>manage>end>detail.html 파일을 복사해서 각 서브메뉴에서 활용하시면 됩니다!

[FEAT] 프로젝트 상세조회 데이터연동

---

src/main/resources/templates/project/manage/end/submenu.html

[FIX] 타임리프 네임스페이스 설정 추가

---

src/main/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectAttachmentDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectAttachment.java
src/main/java/com/greedy/dduckleaf/projectapplication/repository/ProjectAttachmentForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationService.java

프로젝트 신청 시 파머 프로필 이미지를 등록하는 기능 구현했습니다.

[FEAT] 프로젝트 신청 파머 정보 작성 페이지 사진 업로드 기능 구현

---

src/main/resources/templates/report/platformmanager/default.html
src/main/resources/templates/report/platformmanager/list.html
src/main/resources/templates/report/platformmanager/paging.html

default.html파일에 요청 URL 경로 수정해주고, 파라미터 함꼐 전달하여 해당 파라미터로 프로젝트목록을 조회하도록 수정했습니다.
list.html파일을 경우의 수에 따라 재사용할 수 있도록 페이징 코드만 분리해주었습니다.

[DESIGN] 프로젝트 신고 처리상태별 목록조회 화면 수정

---

src/main/resources/templates/mockfunding/list.html

모의펀딩 목록조회 페이지 인풋태그, div태그 등의 속성을 수정했습니다.

[DESIGN] 모의펀딩 목록조회 페이지 수정

---

src/main/resources/templates/mockfunding/detail.html

[DESIGN] 모의펀딩 상세조회 페이지 추가

---

src/main/java/com/greedy/dduckleaf/mockfund/find/controller/MockFundingController.java
src/main/java/com/greedy/dduckleaf/mockfund/find/service/MockFundingService.java
src/test/java/com/greedy/dduckleaf/mockfund/find/repository/MockFundForFundingRepositoryTest.java

[FEAT] 모의펀딩 목록 상세 조회 기능 추가

---

src/main/resources/templates/mockfunding/detail.html
src/main/resources/templates/mockfunding/list.html

상세조회페이지와 목록조회 -> 상세조회 이동을 추가했습니다.

[DESIGN] 모의펀딩 상세조회 페이지 및 목록조회 페이지에서 이동 코드 추가

---

src/main/java/com/greedy/dduckleaf/profile/service/ProfileService.java

[FIX] 프로필 이메일 변경 후 이동 url 수정

---

src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectApplicationInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectBasicInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectExamineHistoryCategoryDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectApplicationInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectExamineHistoryCategory.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectProgressStatus.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/RefundPolicy.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/BankForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/FarmerFinancialInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/FarmerInfoForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/MemberForApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectApplicationInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectAttachmentForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectBasicInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectForApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectRewardCategoryForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectShippingInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/RefundPolicyForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/RewardRegistInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/service/ProjectApplicationService.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/controller/ProjectApplicationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationServiceTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/repository/ProjectForApplicationRepositoryTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/repository/RewardRegistInfoRepositoryTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/service/ProjectApplicationServiceTest.java

관리자 페이지에서 프로젝트 신청 내역 목록 조회하는 기능을 구현했습니다.

[FEAT] 프로젝트 신청내역 목록 조회 기능 구현

---

src/main/resources/static/css/funding.css
src/main/resources/templates/funding/find/supporter/fundingdetailinfo.html
src/main/resources/templates/funding/find/supporter/refundmodal.html
src/main/resources/templates/funding/find/supporter/shippingmodal.html
src/main/resources/templates/funding/regist/shippinginfo.html

[DESIGN] 펀딩정보 수정 페이지 작성

---

src/main/java/com/greedy/dduckleaf/project/finalfield/CodeForProject.java
src/main/java/com/greedy/dduckleaf/refund/regist/entity/Funding.java
src/main/java/com/greedy/dduckleaf/refund/regist/entity/Member.java
src/main/java/com/greedy/dduckleaf/refund/regist/entity/Project.java
src/main/java/com/greedy/dduckleaf/refund/regist/repository/ProjectForRefundingRegistRepository.java
src/main/java/com/greedy/dduckleaf/refund/regist/service/RefundingRegistService.java
src/test/java/com/greedy/dduckleaf/refund/regist/repository/ProjectForRefundingRegistRepositoryTest.java
src/test/java/com/greedy/dduckleaf/refund/regist/service/RefundingRegistServiceTest.java

[FEAT] 환불신청 구현 및 엔티티 작성

---

src/main/java/com/greedy/dduckleaf/project/finalfield/CodeForProject.java
src/main/resources/static/css/funding.css
src/main/resources/templates/funding/find/supporter/fundingdetailinfo.html
src/main/resources/templates/funding/find/supporter/refundmodal.html
src/main/resources/templates/funding/find/supporter/shippingmodal.html
src/main/resources/templates/funding/regist/shippinginfo.html

[DESIGN] 펀딩신청정보 수정 페이지 작성

---

src/main/java/com/greedy/dduckleaf/faq/controller/FaqController.java
src/main/java/com/greedy/dduckleaf/faq/dto/FaqDTO.java
src/main/java/com/greedy/dduckleaf/faq/entity/Faq.java
src/main/java/com/greedy/dduckleaf/faq/service/FaqService.java
src/test/java/com/greedy/dduckleaf/faq/service/FaqServiceTest.java

[FEAT] FAQ 등록 코드 작성

---

src/main/resources/static/css/faq.css
src/main/resources/templates/faq/regist.html

[DESIGN] FAQ 등록 뷰페이지 작성

---

src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectApplicationInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationServiceTest.java

프로젝트 신청 내역에서 파머가 신청 시 작성한 모든 데이터를 볼 수 있는 기능을 구현했습니다.

[FEAT] 프로젝트 신청 내역 상세조회 기능 구현

---

src/main/resources/templates/project/progressing/detail.html
src/main/resources/templates/report/regist.html

등록 성공 시 알러트창을 띄워 성공을 알릴 수 있는 자바스크립트 코드도 추가되었습니다.

[DESIGN] 프로젝트 신고 등록 요청URL 수정

---

src/main/java/com/greedy/dduckleaf/funding/entity/Project.java
src/main/java/com/greedy/dduckleaf/funding/entity/ProjectShippingInfo.java
src/main/java/com/greedy/dduckleaf/funding/entity/RewardShipping.java
src/main/java/com/greedy/dduckleaf/funding/regist/repository/RewardShippingForFundingRegistRepository.java
src/main/java/com/greedy/dduckleaf/funding/regist/service/FundingRegistService.java

[FEAT] 펀딩 등록 시 발송 정보 생성 기능 작성

---

src/main/java/com/greedy/dduckleaf/projectapplication/dto/ExamineProjectStatusDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectExamineHistoryDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ExamineProjectStatus.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectExamineHistory.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectExamineHistoryCategory.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/FarmerFinancialInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectApplicationInfoRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectExamineHistoryForProjectExaminationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationService.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/controller/ProjectExaminationControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/projectexamination/service/ProjectExaminationServiceTest.java

[FEAT] 프로젝트 심사 기능 구현

---

src/main/java/com/greedy/dduckleaf/projectapplication/dto/ProjectAttachmentDTO.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/FarmerInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/Project.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectAttachment.java
src/main/java/com/greedy/dduckleaf/projectapplication/entity/ProjectBasicInfo.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/controller/ProjectApplicationController.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/repository/ProjectAttachmentForProjectApplicationRepository.java
src/main/java/com/greedy/dduckleaf/projectapplication/projectapplication/service/ProjectApplicationService.java

프로젝트 신청 시 대표자 및 정산 정보페이지에서 이미지 업로드 하는 기능을 구현했습니다!

[FEAT] 대표자 및 정산 정보 이미지 업로드 기능 구현

---

src/main/java/com/greedy/dduckleaf/projectapplication/farmerpage/controller/FarmerPageController.java
src/main/java/com/greedy/dduckleaf/projectapplication/farmerpage/service/FarmerPageService.java
src/test/java/com/greedy/dduckleaf/projectapplication/farmerpage/controller/FarmerPageControllerTest.java
src/test/java/com/greedy/dduckleaf/projectapplication/farmerpage/service/FarmerPageServiceTest.java

파머 페이지에서 반환 정책을 조회하는 기능을 구현했습니다.

[FEAT] 파머페이지에서 반환 정책 조회 기능 구현

---

src/main/java/com/greedy/dduckleaf/faq/controller/FaqController.java
src/main/java/com/greedy/dduckleaf/faq/service/FaqService.java

[FEAT] FAQ 수정&삭제 기능 추가

---

src/main/resources/static/css/faq.css
src/main/resources/templates/faq/detail.html
src/main/resources/templates/faq/list.html
src/main/resources/templates/faq/modify.html

FAQ 수정페이지 modify.html을 작성하였습니다.

[DESIGN] FAQ 수정페이지 작성

---

src/main/java/com/greedy/dduckleaf/admin/controller/AdminController.java
src/main/resources/application.yml
src/main/resources/templates/common/userheader.html

1. admin dashboard페이지 포워딩 작성.
2. 라이브 리로드 주석처리.
라이브 리로드 사용하실분은 주석 해제 후 사용하시고
풀 리퀘스트에는 반영 안되게 해주세요~

[FEAT] 공통코드 작성

---

src/main/resources/templates/common/footer.html

푸터 dduckleaf-logo 이미지경로 수정을 위해 footer.html을 변경했습니다.

[STYLE] 푸터 이미지 경로 수정

---

src/main/resources/templates/common/menubar.html

메뉴바 FAQ 링크경로 수정을 위해 menubar.html을 변경했습니다.

[STYLE] 메뉴바 링크경로 수정

---

src/main/resources/templates/faq/detail.html
src/main/resources/templates/faq/list.html
src/main/resources/templates/faq/modify.html
src/main/resources/templates/faq/regist.html

FAQ 페이징 헤더영역을 수정하였습니다
수정한html 목록: list.html, detail.html, regist.html, modify.html

[STYLE] FAQ  페이징, 헤더영역 수정

---

src/main/java/com/greedy/dduckleaf/projectreport/controller/ProjectReportController.java
src/main/resources/templates/common/adminheader.html
src/main/resources/templates/report/membermanager/list.html

관리자 회원관리 메뉴 하위에 회원별 프로젝트신고목록조회를 추가하였습니다.

[FEAT] 회원 프로젝트신고내역 목록조회 기능 추가

---

src/main/java/com/greedy/dduckleaf/shippingmanagement/dto/FundingInfoDTO.java
src/main/java/com/greedy/dduckleaf/shippingmanagement/dto/ShippingAddressDTO.java
src/main/java/com/greedy/dduckleaf/shippingmanagement/entity/FundingInfo.java
src/main/java/com/greedy/dduckleaf/shippingmanagement/entity/RewardShipping.java
src/main/java/com/greedy/dduckleaf/shippingmanagement/entity/ShippingAddress.java

toString으로 인한 stackOverflow 문제 수정

[FIX] 누락된 DTO 및 엔티티 추가 및 오류 해결

---

src/main/java/com/greedy/dduckleaf/projectreport/controller/ProjectReportController.java
src/main/java/com/greedy/dduckleaf/projectreport/find/dto/FarmerInfoDTO.java
src/main/java/com/greedy/dduckleaf/projectreport/find/dto/ProjectDTO.java
src/main/java/com/greedy/dduckleaf/projectreport/find/entity/FarmerInfo.java
src/main/java/com/greedy/dduckleaf/projectreport/find/entity/Project.java

project 엔티티와 farmerInfo를 매핑하고,
project 엔티티에 컬럼 매핑한 필드를 추가하였습니다.

[FIX] 프로젝트 신고내역 목록조회 기능 수정

---

src/main/resources/static/css/faq.css
src/main/resources/templates/faq/regist.html

FAQ 등록화면 regist.html 을 수정했습니다.

[DESIGN] FAQ 등록화면을 수정했습니다.

---

src/main/java/com/greedy/dduckleaf/projectreport/find/service/ProjectReportService.java

답변 등록 시 해당 신고내역의 답변상태가 '답변완료'로 바뀔 수 있도록 수정하였습니다.

[FIX] 프로젝트 신고 답변 등록 기능 수정

---

src/main/resources/templates/report/projectmanager/detail.html

[FIX] 프로젝트 관리 화면에서 프로젝트 신고 답변 등록 기능 수정

---

src/main/java/com/greedy/dduckleaf/funding/dto/FundingDTO.java
src/main/java/com/greedy/dduckleaf/funding/dto/RefundAccountDTO.java
src/main/java/com/greedy/dduckleaf/funding/entity/Funding.java
src/main/java/com/greedy/dduckleaf/funding/regist/controller/FundingRegistController.java
src/main/java/com/greedy/dduckleaf/refund/examine/dto/FundingDTO.java
src/main/java/com/greedy/dduckleaf/refund/examine/entity/Funding.java
src/main/java/com/greedy/dduckleaf/refund/find/dto/FundingDTO.java
src/main/java/com/greedy/dduckleaf/refund/find/entity/Funding.java
src/main/java/com/greedy/dduckleaf/refund/find/entity/FundingCount.java

[HOTFIX] 펀딩엔터티 환불계좌번호 자료형 수정
